apiVersion: apps/v1
kind: Deployment
metadata:
  name: scaletestapp-deployment
  labels:
    app: scaletestapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scaletestapp
  template:
    metadata:
      labels:
        app: scaletestapp
    spec:
      containers:
      - name: app
        image: ghcr.io/yandex-practicum/scaletestapp:latest
        resources:
          limits:
            memory: "30Mi"
          requests:
            memory: "30Mi"